[package]
name = "capella"
version = "0.1.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]

[dependencies]
chrono = "0.2"
futures = "0.1"
lazy_static = "0.2"
regex = "0.2"
tokio-core = "0.1"
tokio-timer = "0.1"
